In [3]:
import pandas as pd

In [8]:
df_excel = pd.read_excel("planilha_preço.xlsx")
df_excel.head(3)

,Data,ID_Pedido,Produto,Quantidade,Preco_Unitario,Regiao
0,2026-06-01,1001,Notebook,1,3500.0,Sudeste
1,2026-06-01,1002,Monitor 24,2,900.0,Sul
2,2026-06-02,1003,Teclado Mecanico,5,250.0,Nordeste

In [16]:
df_info = df_excel.info()
df_info

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Data            6 non-null      datetime64[us]
 1   ID_Pedido       6 non-null      int64
 2   Produto         6 non-null      str
 3   Quantidade      6 non-null      int64
 4   Preco_Unitario  6 non-null      float64
 5   Regiao          6 non-null      str
dtypes: datetime64[us](1), float64(1), int64(2), str(2)
memory usage: 420.0 bytes

In [14]:
df_descricao = df_excel.describe()
df_descricao

                      Data    ID_Pedido  Quantidade  Preco_Unitario
count                    6     6.000000    6.000000        6.000000
mean   2026-06-02 00:00:00  1002.666667    2.166667     1966.666667
min    2026-06-01 00:00:00  1001.000000    1.000000      150.000000
25%    2026-06-01 06:00:00  1001.250000    1.000000      412.500000
50%    2026-06-02 00:00:00  1002.500000    1.500000     2200.000000
75%    2026-06-02 18:00:00  1003.750000    2.750000     3500.000000
max    2026-06-03 00:00:00  1005.000000    5.000000     3500.000000
std                    NaN     1.632993    1.602082     1699.313587

In [25]:
max_duplas = df_excel[["Preco_Unitario", "Quantidade"]].max()
max_duplas

Preco_Unitario    3500.0
Quantidade           5.0
dtype: float64

In [27]:
df_excel["Faturamento total"] = df_excel["Quantidade"] * df_excel["Preco_Unitario"]
df_excel

,Data,ID_Pedido,Produto,Quantidade,Preco_Unitario,Regiao,Faturamento total
0,2026-06-01,1001,Notebook,1,3500.0,Sudeste,3500.0
1,2026-06-01,1002,Monitor 24,2,900.0,Sul,1800.0
2,2026-06-02,1003,Teclado Mecanico,5,250.0,Nordeste,1250.0
3,2026-06-02,1004,Notebook,1,3500.0,Sudeste,3500.0
4,2026-06-03,1005,Mouse Gamer,3,150.0,Centro-Oeste,450.0
5,2026-06-03,1001,Notebook,1,3500.0,Sudeste,3500.0